version: "3.9"

name: pulse-bridge

x-env: &app-env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:8080

  # App settings (override via .env)
  ConnectionStrings__QuartzNet: ${DB_CONN}
  Redis__ConnectionString: ${REDIS_CONN}

  # RabbitMQ settings consumed by Worker/Scheduler
  RabbitMq__Host: rabbitmq
  RabbitMq__User: ${RABBITMQ_USER}
  RabbitMq__Pass: ${RABBITMQ_PASS}

networks:
  edge_net: { driver: bridge }
  app_net: { driver: bridge, internal: true }
  data_net: { driver: bridge, internal: true }

services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
      - --providers.docker=true
      #- --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      # For local HTTPS, uncomment and provide certs
      # - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [edge_net, app_net]
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: pulse-bridge-web:1.0
    container_name: pulse-bridge-web
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`ui.localtest.me`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.services.web.loadbalancer.server.port=80
    networks: [app_net]
    depends_on: [traefik]
    restart: unless-stopped

  api:
    image: pulse-bridge-api:1.0
    container_name: pulse-bridge-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localtest.me`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=8080
      

      # --- CORS middleware (for UI -> API) ---
      - traefik.http.routers.api.middlewares=api-cors@docker
      - traefik.http.middlewares.api-cors.headers.accesscontrolalloworiginlist=http://ui.localtest.me
      # Methods needed by SignalR (negotiate = POST; ws upgrade = GET; and preflight = OPTIONS)
      - traefik.http.middlewares.api-cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS
      # Headers SignalR typically sends (include Authorization if you use JWT)
      - traefik.http.middlewares.api-cors.headers.accesscontrolallowheaders=Authorization,Content-Type,X-Requested-With,X-SignalR-User-Agent
      # If you prefer, you can allow all headers instead of listing:
      # - traefik.http.middlewares.api-cors.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.api-cors.headers.accesscontrolallowcredentials=true
      # Optional niceties:
      - traefik.http.middlewares.api-cors.headers.addvaryheader=true
      - traefik.http.middlewares.api-cors.headers.accesscontrolmaxage=86400
    networks: [app_net]
    restart: unless-stopped

  worker:
    image: pulse-bridge-worker:1.0
    container_name: pulse-bridge-worker
    environment: *app-env
    depends_on:
      - rabbitmq
      - api
    networks: [app_net, data_net]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10

  scheduler:
    image: pulse-bridge-scheduler:1.0
    container_name: pulse-bridge-scheduler
    environment:
      <<: *app-env
      Quartz__JobStore: AdoNet
      ConnectionStrings__QuartzNet: ${DB_CONN}
    depends_on:
      - sql
      - rabbitmq
    networks: [app_net, data_net]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pulse-bridge-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    networks: [edge_net, data_net]
    ports:
      - "1433:1433"   # only expose if you really need external access (for dev only)
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7.2
    command: ["redis-server", "--appendonly", "yes"]
    container_name: pulse-bridge-redis
    networks: [data_net]
    #ports:
      #- "6379:6379"   # same note: expose only if needed (for dev only)
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks: [data_net]
    #ports:
      #- "15672:15672" # mgmt UI (dev only)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mssqldata:
  redisdata:
  rabbitmq_data:
