http:
  serversTransports:
    backends:
      maxIdleConnsPerHost: 64
      forwardingTimeouts:
        dialTimeout: 10s                 # connect to container
        responseHeaderTimeout: 60s       # time to first byte from app
        idleConnTimeout: 120s            # keep idle conns
  middlewares:
    retry-2:
      retry:
        attempts: 2
        initialInterval: 100ms
        
    gzip: { compress: {} }
    secure-headers:
      headers:
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
tls:
  certificates:
    - certFile: /certs/dev.crt
      keyFile: /certs/dev.key