http:
  middlewares:
    gzip: { compress: {} }
    secure-headers:
      headers:
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
tls:
  certificates:
    - certFile: /certs/dev.crt
      keyFile: /certs/dev.key
